# Copy pasted from inrev-asset-tool

AllCops:
  Exclude:
    - 'bin/{rails,rake,webpack,webpack-dev-server,yarn}'
    - 'config/environments/**/*'
    - 'config/initializers/**/*'
    - 'config/puma.rb'
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'public/**/*'
    - 'tmp/**/*'
    - 'untracked/**/*'
    - 'app/models/legacy/*'
    - 'vendor/**/*'
  TargetRubyVersion: 3.4
  NewCops: enable

plugins:
  - rubocop-rspec

Layout/DotPosition:
  EnforcedStyle: leading
Layout/ExtraSpacing:
  Enabled: false
Layout/AssignmentIndentation:
  Enabled: true
  EnforcedStyle: same_line
Layout/EndAlignment:
  Enabled: true
  EnforcedStyleAlignWith: variable
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/AbcSize:
  Max: 175
Metrics/BlockLength:
  Max: 175
  Exclude:
    - config/routes.rb
    - spec/**/*.rb
Metrics/ClassLength:
  Max: 1000
Metrics/CyclomaticComplexity:
  Max: 50
Metrics/MethodLength:
  Max: 175
Metrics/ModuleLength:
  Max: 1000
Metrics/ParameterLists:
  Max: 12
Metrics/PerceivedComplexity:
  Max: 50

Naming/VariableNumber:
  Enabled: false

# Trailing commas make for clearer diffs because the last line won't appear
# to have been changed, as it would if it lacked a comma and had one added.
Style/AccessModifierDeclarations:
  EnforcedStyle: 'inline'
Style/BlockComments:
  Enabled: false
Style/CaseLikeIf:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Style/FormatStringToken:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/HashSyntax:
  StyleGuide: '#hash-literals'
  Enabled: true
  VersionAdded: '0.9'
  VersionChanged: '1.24'
  EnforcedStyle: ruby19
  EnforcedShorthandSyntax: always
  UseHashRocketsWithSymbolValues: false
  PreferHashRocketsForNonAlnumEndingSymbols: false
Style/Lambda:
  EnforcedStyle: literal
# Cop supports --auto-correct.
# Configuration parameters: PreferredDelimiters.
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    # Using `[]` for string arrays instead of `()`, since normal arrays are
    # indicated with `[]` not `()`.
    '%w': '[]'
    '%W': '[]'
Style/RescueModifier:
  Enabled: false
Style/RescueStandardError:
  Enabled: true
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
